#!/bin/bash

# This was tested to work on Ubuntu 15.04.
# Allows the container to:
# - use the camera
# - read /etc/localtime
# - talk to X server
# - talk to pulseaudio

# Allow all hosts to connect to X server.
# TODO: Maybe not very secure. Find a way to only allow skype from this
# container.
xhost +

docker run -it --rm \
	--device /dev/video0 \
	-v /etc/localtime:/etc/localtime:ro \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v /run/user/$(id -u)/pulse:/run/pulse \
	-e DISPLAY=unix$DISPLAY \
	--name skype \
	suligap/skype

# Restrict access to X server again.
xhost -
