#!/bin/bash

docker run -it --rm \
	--device /dev/video0 \
	-v /etc/localtime:/etc/localtime:ro \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-v /run/user/$(id -u)/pulse:/run/pulse \
	-e DISPLAY=unix$DISPLAY \
	--name skype \
	suligap/skype
